//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class oe_examsresult
    {
        public int examid { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> q_id { get; set; }
        public Nullable<int> c_ans { get; set; }
        public Nullable<int> u_ans { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
    }
}
