//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class oe_members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oe_members()
        {
            this.oe_exams = new HashSet<oe_exams>();
        }
    
        public int mid { get; set; }
        public string lname { get; set; }
        public string Enq_No { get; set; }
        public string Mobileno { get; set; }
        public string pwd { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dlv { get; set; }
        public Nullable<System.DateTime> dr { get; set; }
        public Nullable<int> Course_id { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oe_exams> oe_exams { get; set; }
    }
}
